name: Tests

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
            - name: npm install
              run: npm ci
            - name: check code style
              run: npm run lint
            - name: check formatting
              run: npx prettier --check src/
            - name: run type checks
              run: npm run type-check
            - name: run unit tests
              run: npm run test:unit
            - name: test build process
              run: npm run build
            - name: check for known vulnerabilities
              run: npm audit --audit-level=moderate
            - name: install playwright browsers
              run: npx playwright install --with-deps chromium
            - name: run e2e tests
              run: npm run test:e2e
